Alert
Kotaro0722/Kotaro-frontend-basic-2022-todoapp pull request #12
Opened 2023-04-10 08:05 UTC by Kotaro0722

2023-04-26 07:01 UTC, SakaueYae reviewed
アラートのフェードイン、フェードアウト表示ができていないため、そこの修正もお願いします🙇‍♀️

2023-05-01 12:27 UTC, SakaueYae commented on src/components/Organisms/TodoCard/index.jsx
> +    top: 40px;
面談のときに指摘できず、すみません🙇‍♀️TodoCardのtopを追加している状態なので、Alert内のtopを修正してみてください！

2023-05-06 02:05 UTC, higashiji2000 requested changes
ページをロードした瞬間から一番下のTODOが編集モードになっているので、そこだけ修正お願いします！
ToDoCardのtaskListがinitializingというプロパティをもっていると思うので、それを適切に変更し、TaskのdefaultIsEditingを機能させてあげる必要があると思います。

2023-05-06 02:05 UTC, higashiji2000 commented on src/components/Organisms/AlertManager/index.jsx
> +    }
```suggestion
    useEffect(() => {
      const setInterval = () => {
      setTimeout(() => {
        AlertHandlerContext.closeAlert();
      }, 5000);
    };
  
    if (AlertHandlerContext.visible == true) {
      setInterval();
    }
```
今回はシンプルなコンポーネントなので現状でも全く問題ありませんが、このようにuseEffectの中で関数を宣言することによってスコープが閉じ可読性が上がるというメリットが有ります。複雑なコンポーネントを作る際には意識してみてください！

スコープについて：https://jsprimer.net/basic/function-scope/

2023-05-10 03:48 UTC, higashiji2000 approved these changes
LGTM🥳

2023-05-22 00:27 UTC, merged